2023-06-13 14:34:32,744 INFO    MainThread:517 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2023-06-13 14:34:32,745 INFO    MainThread:517 [wandb_setup.py:_flush():76] Configure stats pid to 517
2023-06-13 14:34:32,745 INFO    MainThread:517 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-06-13 14:34:32,746 INFO    MainThread:517 [wandb_setup.py:_flush():76] Loading settings from /content/gdrive/MyDrive/AAU_Project/Goal_Oriented_Federated_Learning/wandb/settings
2023-06-13 14:34:32,746 INFO    MainThread:517 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-06-13 14:34:32,746 INFO    MainThread:517 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-06-13 14:34:32,747 INFO    MainThread:517 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2023-06-13 14:34:32,748 INFO    MainThread:517 [wandb_init.py:_log_setup():507] Logging user logs to /content/gdrive/MyDrive/AAU_Project/Goal_Oriented_Federated_Learning/wandb/run-20230613_143432-qkb6i4ar/logs/debug.log
2023-06-13 14:34:32,748 INFO    MainThread:517 [wandb_init.py:_log_setup():508] Logging internal logs to /content/gdrive/MyDrive/AAU_Project/Goal_Oriented_Federated_Learning/wandb/run-20230613_143432-qkb6i4ar/logs/debug-internal.log
2023-06-13 14:34:32,749 INFO    MainThread:517 [wandb_init.py:init():547] calling init triggers
2023-06-13 14:34:32,749 INFO    MainThread:517 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'random_seed': 0, 'num_clients': 20, 'alpha': 1000000.0, 'learning_rate': 0.001, 'num_communication_rounds': 400, 'server_select_fraction': 0.5, 'client_iterations': 1, 'experiment': 'random', 'server_selection': 'random', 'client_sampling': 'random', 'client_transmission': 'always'}
2023-06-13 14:34:32,750 INFO    MainThread:517 [wandb_init.py:init():571] re-initializing run, found existing run on stack: vsn6k5uf
2023-06-13 14:34:32,752 INFO    MainThread:517 [wandb_run.py:_finish():1890] finishing run pringlesinghal/shapley-fl/vsn6k5uf
2023-06-13 14:34:32,844 ERROR   MainThread:517 [wandb_init.py:init():1180] error
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 1152, in init
    run = wi.init()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 581, in init
    latest_run.finish()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 332, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 1881, in finish
    return self._finish(exit_code, quiet)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 1909, in _finish
    manager._inform_finish(run_id=self._run_id)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_manager.py", line 224, in _inform_finish
    svc_iface._svc_inform_finish(run_id=run_id)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/service/service_sock.py", line 54, in _svc_inform_finish
    self._sock_client.send(inform_finish=inform_finish)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
